name: test-it-with-github-actions
run-name: ${{ github.actor }} is Trying GitHub Actions
on: [push]

jobs:
  test-python2:
    runs-on: ubuntu-latest
   # strategy:
   #  matrix:
   #     python-version: ["2.6", "2.7", "3.10",  "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 2.7
        uses: actions/setup-python@v4
        with:
          python-version: 2.7
          
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install GRO2LAM setup
        run: python setup -t
        
  test-python3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install GRO2LAM setup
        run: python setup -t     

        
